name: Node CI to gh-pages

on:
  push:
    branches: 
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and deploy to gh-pages
      run: |
        npm install
        git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
        git config --global user.name github-actions
        git remote set-url origin https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY
        npm run build
        npm run deploy
